// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvRKXM38I-isueVDPyVBxtGL8zfFi0xHg',
    appId: '1:263266137209:web:c55df2a2eb97d3967c90a8',
    messagingSenderId: '263266137209',
    projectId: 'electx',
    authDomain: 'electx.firebaseapp.com',
    storageBucket: 'electx.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY_mP5NDMprtwvpChAuoylf32H3bY3QDo',
    appId: '1:263266137209:android:80eb08007767dafc7c90a8',
    messagingSenderId: '263266137209',
    projectId: 'electx',
    storageBucket: 'electx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUMUwfKs1WGbFUIu65JtHFZ3kHxurTOTo',
    appId: '1:263266137209:ios:201d592e3c346a2f7c90a8',
    messagingSenderId: '263266137209',
    projectId: 'electx',
    storageBucket: 'electx.firebasestorage.app',
    iosBundleId: 'com.example.electxNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUMUwfKs1WGbFUIu65JtHFZ3kHxurTOTo',
    appId: '1:263266137209:ios:201d592e3c346a2f7c90a8',
    messagingSenderId: '263266137209',
    projectId: 'electx',
    storageBucket: 'electx.firebasestorage.app',
    iosBundleId: 'com.example.electxNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvRKXM38I-isueVDPyVBxtGL8zfFi0xHg',
    appId: '1:263266137209:web:aea61926226168437c90a8',
    messagingSenderId: '263266137209',
    projectId: 'electx',
    authDomain: 'electx.firebaseapp.com',
    storageBucket: 'electx.firebasestorage.app',
  );
}
